using System.Collections.Generic;

namespace VistaDB.Diagnostic
{
  public class Errors : Dictionary<int, string>
  {
    private string assemblyVersion = "4.3.3.34";
    public const int Nonsupported = 10;
    public const int dda_NonSupportedFileExtension = 11;
    public const int lic_Invalid = 25;
    public const int lic_WrongVersion = 26;
    public const int dda_UpdateSpecification = 50;
    public const int dda_InvalidVDBFormat = 51;
    public const int dda_UpdateFTSSpecification = 52;
    public const int dda_InvalidPageSize = 53;
    public const int dda_NewerSpecification = 54;
    public const int dda_CreateStorage = 100;
    public const int dda_OpenStorage = 101;
    public const int dda_CreateHeader = 102;
    public const int dda_ActivateHeader = 103;
    public const int dda_ActivateHeaderStructure = 104;
    public const int dda_ReadHeader = 105;
    public const int dda_WriteHeader = 106;
    public const int dda_AllocateRowStructure = 107;
    public const int dda_RowExceedsPage = 167;
    public const int dda_StorageReadOnlyMode = 108;
    public const int dda_RowsetExlusiveMode = 109;
    public const int dda_ReadStorage = 110;
    public const int dda_WriteStorage = 111;
    public const int dda_DatastorageDeclaration = 112;
    public const int dda_CreateDatabase = 113;
    public const int dda_CreateIsolatedDatabase = 114;
    public const int dda_CreateTemporaryDatabase = 115;
    public const int dda_EncryptionKeyInvalid = 116;
    public const int dda_OpenDatabase = 117;
    public const int dda_OpenIsolatedDatabase = 118;
    public const int dda_CreateTable = 119;
    public const int dda_AlterTable = 120;
    public const int dda_DropTable = 121;
    public const int dda_TableToDropOpened = 122;
    public const int dda_CreateTableHeader = 123;
    public const int dda_EmptyTableSchema = 124;
    public const int dda_OpenTable = 125;
    public const int dda_NonExistedTable = 126;
    public const int dda_NonExistedIndex = 127;
    public const int dda_CloseTable = 128;
    public const int dda_CloseStorage = 129;
    public const int dda_CreateIndex = 130;
    public const int dda_DropIndex = 131;
    public const int dda_CannotDropFKIndex = 132;
    public const int dda_EmptyIndexInformation = 133;
    public const int dda_ActivateIndex = 134;
    public const int dda_ActivateDatabase = 135;
    public const int dda_DeactivateIndex = 136;
    public const int dda_CreateDefaultRow = 137;
    public const int dda_ActivateDefaultRow = 138;
    public const int dda_ActivateNodeAtPosition = 139;
    public const int dda_SchemaChanges = 140;
    public const int dda_CompactFrameworkMode = 141;
    public const int dda_PrimaryKeyContainsNull = 142;
    public const int dda_PrimaryKeySingle = 143;
    public const int dda_PrimaryKeyRefencedInDelete = 144;
    public const int dda_DuplicateTableName = 145;
    public const int dda_DuplicateIndexName = 146;
    public const int dda_DuplicateColumnName = 147;
    public const int dda_IndexKeyColumnCountExceeds = 149;
    public const int dda_IndexKeyColumnInvalid = 150;
    public const int dda_InvalidName = 152;
    public const int dda_ColumnType = 153;
    public const int dda_MaximumColumns = 154;
    public const int dda_FtsActiveIndex = 155;
    public const int dda_FullTextSingle = 156;
    public const int dda_DuplicateTimestamp = 157;
    public const int dda_IsolateStorageAccessMode = 158;
    public const int dda_CannotRenameFKIndex = 159;
    public const int dda_ActivateLockPolicy = 160;
    public const int dda_LockStorage = 161;
    public const int dda_LockStreamPosition = 162;
    public const int dda_LockTimeout = 163;
    public const int dda_LockRow = 164;
    public const int dda_UnlockRow = 165;
    public const int dda_ReleaseLocks = 166;
    public const int dda_Filter = 170;
    public const int dda_DefaultValueFault = 171;
    public const int dda_ConstraintFault = 172;
    public const int dda_ReadonlyFault = 173;
    public const int dda_NullFault = 174;
    public const int dda_NonSupportedDataType = 179;
    public const int dda_TableClosed = 180;
    public const int dda_InvalidColumnByName = 181;
    public const int dda_InvalidColumnByIndex = 182;
    public const int dda_NullValue = 183;
    public const int dda_IdentityExist = 184;
    public const int dda_IdentityNonExist = 185;
    public const int dda_SetIdentity = 186;
    public const int dda_DropIdentity = 187;
    public const int dda_SeedNullValue = 188;
    public const int dda_StepNullValue = 189;
    public const int dda_InvalidIdentityStep = 190;
    public const int dda_NonSupportedIdentity = 191;
    public const int dda_DefaultValueNonExist = 192;
    public const int dda_SetDefaultValue = 193;
    public const int dda_DropDefaultValue = 194;
    public const int dda_ConstraintNotExist = 195;
    public const int dda_SetConstraint = 196;
    public const int dda_DropConstraint = 197;
    public const int dda_NonSupportedDefaultValue = 198;
    public const int dda_PrimaryKeyReferenced = 199;
    public const int dda_CreateForeignKey = 200;
    public const int dda_DropForeignKey = 201;
    public const int dda_PrimaryKeyNotFound = 202;
    public const int dda_PrimaryKeyCannotBeSelfReferenced = 203;
    public const int dda_RelationshipExist = 204;
    public const int dda_RelationshipDoesNotExist = 205;
    public const int dda_PrimaryKeyIdenticalForeignKey = 206;
    public const int dda_AlterSystemColumn = 207;
    public const int dda_ModifySystemTable = 208;
    public const int dda_DropSyncTable = 209;
    public const int dda_ActivateSyncService = 210;
    public const int dda_DeactivateSyncService = 211;
    public const int dda_TombstoneName = 212;
    public const int dda_AnchorTablename = 213;
    public const int dda_CreateRow = 250;
    public const int dda_UpdateRow = 251;
    public const int dda_DeleteRow = 252;
    public const int dda_ActivateLink = 253;
    public const int dda_CreateLink = 254;
    public const int dda_CreateLinks = 255;
    public const int dda_UpdateLink = 256;
    public const int dda_UpdateLinks = 257;
    public const int dda_DeleteLink = 258;
    public const int dda_DeleteLinks = 259;
    public const int dda_InvalidRowInUpdate = 260;
    public const int dda_InvalidRowInDelete = 261;
    public const int dda_RowOutdated = 262;
    public const int dda_CannotFindKey = 270;
    public const int dda_CannotSynchKey = 271;
    public const int dda_InvalidOrderToFindKey = 272;
    public const int dda_IncorrectString = 280;
    public const int dda_CompileExpression = 281;
    public const int dda_CompileKeyExpression = 282;
    public const int dda_InvalidExpression = 285;
    public const int dda_ParenthesisMismatch = 286;
    public const int dda_InvalidDelimiter = 287;
    public const int dda_InvalidParameter = 288;
    public const int dda_VDBType = 289;
    public const int dda_ExpressionTypeCheck = 290;
    public const int dda_InvalidLogicalExpression = 291;
    public const int dda_EvaluateOperator = 292;
    public const int dda_InvalidIfElse = 293;
    public const int dda_UnexpectedThen = 294;
    public const int dda_UnexpectedElse = 295;
    public const int dda_MissingStringDelimiter = 296;
    public const int dda_IncompleteExpression = 297;
    public const int dda_InvalidOperation = 298;
    public const int dda_InvalidFloatFormat = 299;
    public const int dda_DynamicRange = 300;
    public const int dda_StringExceedMaximum = 301;
    public const int dda_DatatypeConversion = 302;
    public const int dda_InvalidCharLength = 303;
    public const int dda_InvalidPageCount = 304;
    public const int dda_InitSpool = 305;
    public const int dda_EvaluateKey = 307;
    public const int dda_EvaluateExpression = 308;
    public const int dda_DuplicateKey = 309;
    public const int dda_CannotAssignEnvironmentVariable = 320;
    public const int dda_CannotAlterRelationship = 321;
    public const int dda_NodeEncryption = 330;
    public const int dda_NodeDecryption = 331;
    public const int dda_DataImport = 332;
    public const int dda_DataExport = 333;
    public const int dda_PackStorage = 334;
    public const int dda_ZapStorage = 335;
    public const int dda_PackDatabase = 336;
    public const int dda_ReadOnlyMode = 337;
    public const int dda_SharedMode = 338;
    public const int dda_CleanStorage = 339;
    public const int dda_BeforeInsertingRow = 340;
    public const int dda_AfterInsertingRow = 341;
    public const int dda_BeforeUpdatingRow = 342;
    public const int dda_AfterUpdatingRow = 343;
    public const int dda_AfterDeletingRow = 345;
    public const int dda_InitRecycling = 346;
    public const int dda_PackViaDDA = 347;
    public const int dda_ExportTable = 360;
    public const int dda_InvalidClrProcedureName = 380;
    public const int dda_DuplicateClrProcedureName = 381;
    public const int dda_ParametersNumberInClrProcedure = 382;
    public const int dda_ClrProcedureNotRegistered = 383;
    public const int dda_ClrProcedureFillRowNotRegistered = 384;
    public const int dda_ClrProcedureReferenced = 385;
    public const int dda_ClrProcedureRegisterFailed = 386;
    public const int dda_ClrProcedureRemoveFailed = 387;
    public const int dda_ClrProcedureInvokeFailed = 388;
    public const int dda_AssemblyNameRegistered = 389;
    public const int dda_AssemblyNotRegistered = 390;
    public const int dda_AssemblyAddFault = 391;
    public const int dda_AssemblyUpdateFault = 392;
    public const int dda_AssemblyDeleteFault = 393;
    public const int dda_DuplicateClrTriggerName = 394;
    public const int dda_ClrTriggerRegisteringFault = 395;
    public const int dda_ClrTriggerUnregisteringFault = 396;
    public const int dda_ClrTriggerNotRegistered = 397;
    public const int dda_ClrTriggerReferenced = 398;
    public const int dda_ClrTriggerInvalidEvent = 399;
    public const int dda_DuplicateSPName = 400;
    public const int dda_SPRegisteringFault = 401;
    public const int dda_SPUnregisteringFault = 402;
    public const int dda_BeginTransaction = 450;
    public const int dda_CommitTransaction = 451;
    public const int dda_RollbackTransaction = 452;
    public const int dda_CreateTransactionLogTable = 453;
    public const int dda_OpenTransactionLogTable = 454;
    public const int dda_TransactionConcurrency = 455;
    public const int dda_IncorrectTpIsolationLevel = 456;
    public const int dda_NestedTransactionsNotSupported = 457;
    public const int dda_RollbackHasNoBegin = 458;
    public const int dda_CommitHasNoBegin = 459;
    public const int dda_TransactionModeOff = 460;
    public const int dda_EncryptionKeyEmpty = 461;
    public const int dda_TransactionModeOnlyOff = 462;
    public const int sql_ExpectedSymbol = 500;
    public const int sql_InvalidParameterCount = 501;
    public const int sql_ExpectedExprButFound = 502;
    public const int sql_UnterminatedString = 503;
    public const int sql_UnterminatedTableName = 504;
    public const int sql_UnterminatedColumnName = 505;
    public const int sql_UnterminatedComment = 506;
    public const int sql_ExpectedExpression = 507;
    public const int sql_UnknownDataType = 508;
    public const int sql_InvalidStatement = 509;
    public const int sql_InvalidParameterDataType = 550;
    public const int sql_NestedAggregateFunction = 551;
    public const int sql_PatternMustBeString = 552;
    public const int sql_InvalidPatternEscapeSymbol = 553;
    public const int sql_UnterminatedPattern = 554;
    public const int sql_InvalidPatternFirstCharacter = 555;
    public const int sql_UnexpectedError = 556;
    public const int sql_InvalidJoinCondition = 557;
    public const int sql_InvalidOperandDataType = 558;
    public const int sql_InvalidLikeMatchExpression = 559;
    public const int sql_InvalidUsingOfIS = 560;
    public const int sql_InvalidExprInResultColumn = 561;
    public const int sql_AggColumnNotInGroupBy = 562;
    public const int sql_TableAliasDuplicated = 563;
    public const int sql_ExpectedBooleanExpression = 564;
    public const int sql_WhereCannotHaveAggregate = 565;
    public const int sql_ColumnDoesNotExist = 567;
    public const int sql_ExprAlreadyPresentInGroup = 568;
    public const int sql_ExprNotPresentInGroup = 569;
    public const int sql_InvalidHavingClauseCondition = 570;
    public const int sql_InvalidHavingExpressions = 571;
    public const int sql_TableNotExist = 572;
    public const int sql_InvalidGroupWithoutAggregate = 573;
    public const int sql_InvalidGroupWithAggregate = 574;
    public const int sql_InvalidHavingWithoutAggregate = 575;
    public const int sql_ExpectedKeyword = 576;
    public const int sql_InvalidUnionColumnCount = 577;
    public const int sql_InvalidUnionColumnTypes = 578;
    public const int sql_SameColumnInSomeTables = 579;
    public const int sql_InvalidGroupStatic = 580;
    public const int sql_CaseMustHaveWhen = 581;
    public const int sql_CaseWhenMustBeBoolean = 582;
    public const int sql_CaseWhenMustBeInputDataType = 583;
    public const int sql_InvalidCaseResultDataType = 584;
    public const int sql_InvalidTableName = 585;
    public const int sql_InvalidColumnName = 586;
    public const int sql_InsertColumnFewerThanValues = 587;
    public const int sql_InsertColumnMoreThanValues = 588;
    public const int sql_InsertColumnFewerThanSelect = 589;
    public const int sql_InsertSelectFewerThanColumn = 590;
    public const int sql_InvalidQueryIndex = 591;
    public const int sql_InvalidToken = 592;
    public const int sql_InvalidCreateDatabaseParams = 593;
    public const int sql_CreateTableColumnsDuplicated = 594;
    public const int sql_CreateTableConstraintDuplicated = 595;
    public const int sql_PrimaryKeyDuplicated = 596;
    public const int sql_TwoClusteredIndexes = 597;
    public const int sql_InvalidForeignKeyCount = 598;
    public const int sql_IdentityAndDefaultValue = 599;
    public const int sql_PrimaryKeyDoesNotExist = 600;
    public const int sql_InvalidPrimaryKeyInReferences = 601;
    public const int sql_InvalidColumnCountInView = 602;
    public const int sql_ViewNameDuplicated = 603;
    public const int sql_SubQueryIsReadOnly = 604;
    public const int sql_ViewIsReadOnly = 605;
    public const int sql_ViewNotExist = 606;
    public const int sql_FunctionNotExist = 607;
    public const int sql_InvalidIdentifier = 608;
    public const int sql_StoredProcIsReadOnly = 609;
    public const int sql_FirstParameterMustBeObject = 610;
    public const int sql_ExpectedOutParameter = 611;
    public const int sql_FillRowDoesNotExist = 612;
    public const int sql_AssemblyNameNotDefined = 613;
    public const int sql_InvalidCLRProcParamType = 614;
    public const int sql_CLRProcExecutionError = 615;
    public const int sql_ParamNotDeclared = 616;
    public const int sql_ReservedWordNameOrAlias = 617;
    public const int sql_ExpectedConstraintEnd = 618;
    public const int sql_InvalidConstraintExpr = 619;
    public const int sql_ParamRedeclaration = 620;
    public const int sql_InvalidParamName = 621;
    public const int sql_ConstraintNotExist = 622;
    public const int sql_DatabaseNotOpened = 623;
    public const int sql_InvalidDataTypeSpec = 624;
    public const int sql_DataTypeLenIsTooLong = 625;
    public const int sql_InvalidSchemaName = 627;
    public const int sql_InvalidNewNameInRename = 628;
    public const int sql_InvalidObjectTypeInRename = 629;
    public const int sql_DuplicateAction = 630;
    public const int sql_InvalidTriggerDeclaration = 631;
    public const int sql_IncorrectSyntax = 632;
    public const int sql_InvalidFtsPattern = 634;
    public const int sql_InvalidCaseSyntax = 635;
    public const int sql_FtsIndexRequired = 636;
    public const int sql_OnlySingleExpressionInSelectList = 637;
    public const int sql_InvalidParamForm = 638;
    public const int sql_InvalidOutParam = 639;
    public const int sql_TooManyArguments = 640;
    public const int sql_ParameterIsNotDefined = 641;
    public const int sql_AssignValueSelect = 642;
    public const int sql_InvalidContinueUsnig = 643;
    public const int sql_InvalidBreakUsing = 644;
    public const int sql_wrongRowGuidCol = 655;
    public const int sql_AggregateTableAsterix = 656;
    public const int sql_AggregateAllAsterix = 657;
    public const int sql_AggregateDistinctAsterix = 658;
    public const int sql_CustomError = 50000;
    public const int sql_WithIsUnsupported = 660;
    public const int sql_NumericParameterRequired = 661;
    public const int sql_UnableToImplicitCastType = 662;
    public const int sql_IncorrectTypeProvided = 663;
    public const int ado_SupportedOnlyCommand = 1001;
    public const int ado_UnknownDataType = 1002;
    public const int ado_SecondDataReader = 1003;
    public const int ado_ChangePropWhileDataAdapter = 1004;
    public const int ado_ChangePropWhileConnOpened = 1005;
    public const int ado_InvalidNameSuffix = 1006;
    public const int ado_InvalidNamePrefix = 1007;
    public const int ado_CommandTextEmpty = 1008;
    public const int ado_ContextConnNotAvailable = 1009;
    public const int ado_CBSchemaCannotBeGenerated = 1010;
    public const int ado_ConnectionMustBeAssigned = 1011;
    public const int ado_ConnectionMustBeOpened = 1012;
    public const int ado_ReadCommittedIsolationOnly = 1013;
    public const int ado_KeywordNotSupported = 1014;
    public const int dt_Position = 2010;
    public const int dt_LastKeyPosition = 2011;
    public const int dt_RowsAdded = 2012;
    public const int dt_SetScope = 2013;
    public const int dt_ResetScope = 2014;
    public const int dt_SetFilter = 2015;
    public const int dt_RowIsNotExist = 2016;
    public const int dt_FindRow = 2017;
    public const int dt_ActiveIndex = 2018;
    public const int dt_UpdateRow = 2019;
    public const int dt_HideNewRow = 2020;
    public const int dt_InsertRow = 2021;
    public const int dt_DeleteRow = 2022;
    public const int dt_OpenTable = 2023;
    public const int dt_Reset = 2024;
    public const int dt_ReadSchema = 2040;
    public const int dt_ReadData = 2041;

    internal Errors()
      : base(350)
    {
      ReadResources();
    }

    private void ReadResources()
    {
      Add(10, "Method or property not supported");
      Add(11, "Database file extension not supported: ");
      Add(25, "Your VistaDB license file appears to be invalid or corrupt.");
      Add(26, "The VistaDB license file is for a newer version of VistaDB.  Please update your key by reinstalling.");
      Add(50, "Database schema specification changed. Pack database to update your database to latest version.");
      Add(54, "Database schema specification is newer than what this version of VistaDB supports. Database cannot be used.");
      Add(51, "File is not a valid VistaDB 4 database");
      Add(52, "FullTextSearch index specification changed. Pack database to update database.");
      Add(53, "Database page size is outside the allowable range.");
      Add(100, "Cannot create data storage or file: ");
      Add(101, "Cannot open data storage or file: ");
      Add(102, "Cannot create data storage header: ");
      Add(103, "Cannot activate data storage header: ");
      Add(104, "Cannot initialize header data of: ");
      Add(105, "Cannot read header of: ");
      Add(106, "Cannot write header of: ");
      Add(107, "Allocate row structure in data storage: ");
      Add(167, "Row structure data size exceeds the database page size: ");
      Add(108, "Incompatible mode. Database storage is read-only. You cannot access it for write operations: ");
      Add(109, "Incompatible exclusive access mode. Only single table instance may be opened: ");
      Add(110, "Cannot read data storage or file: ");
      Add(111, "Cannot write data storage or file: ");
      Add(112, "Cannot declare new data storage: ");
      Add(113, "Cannot create database: ");
      Add(114, "Cannot create database in isolated storage");
      Add(115, "Cannot create temporary database");
      Add(116, "Invalid encryption key. Unable to decode database with given encryption key: ");
      Add(117, "Cannot open database: ");
      Add(118, "Cannot open database in isolated storage");
      Add(119, "Cannot create table: ");
      Add(120, "Cannot rename or alter table: ");
      Add(121, "Cannot drop table: ");
      Add(122, "Table is opened and cannot be dropped at current moment");
      Add(123, "Cannot create table header: ");
      Add(124, "At least one column should be created in the table: ");
      Add(125, "Cannot open table: ");
      Add(126, "Table not found: ");
      Add(sbyte.MaxValue, "Index not found: ");
      Add(128, "An error happened while table was being closed: ");
      Add(129, "An error happened while data storage was being closed");
      Add(130, "Cannot create index");
      Add(131, "Cannot delete index: ");
      Add(132, "Cannot explicitly delete foreign key index: ");
      Add(133, "Index information absent: ");
      Add(134, "Cannot activate index");
      Add(135, "Cannot activate database");
      Add(136, "Index deactivation error");
      Add(137, "Cannot create default values in table: ");
      Add(138, "Cannot initialize default values in table: ");
      Add(139, "Cannot access node at position: ");
      Add(140, "Schema was changed by another instance. Data storage must be reopened: ");
      Add(141, "You cannot use this database opening mode on Compact Framework: ");
      Add(142, "Primary key cannot contains column with null value: ");
      Add(143, "The primary key already exists. Only one primary key index allowed");
      Add(144, "Table contains primary key referenced and cannot be deleted");
      Add(145, "Duplicate table name: ");
      Add(146, "Duplicate index name: ");
      Add(147, "Duplicate Column name : ");
      Add(149, "Index key column count exceeds maximum allowed count: ");
      Add(150, "Index key cannot contain the column: ");
      Add(152, "Invalid name or alias: ");
      Add(153, "Unsupported VistaDB type");
      Add(154, "Column number exceeds maximum allowed: ");
      Add(155, "Full text index cannot be made active.  Pack the database to repair the index.");
      Add(156, "The full text index already exists. Only one full text index allowed per table");
      Add(157, "Row cannot contain two and more columns with same VistaDB.Timestamp data type");
      Add(158, "Isolated database does not support access mode: ");
      Add(159, "Cannot rename foreign key index");
      Add(160, "Cannot use lock policy by storage: ");
      Add(161, "Cannot lock data storage: ");
      Add(162, "Cannot lock file position: ");
      Add(163, "Lock timeout expired");
      Add(164, "Cannot lock row: ");
      Add(165, "Cannot unlock row: ");
      Add(166, "Cannot release locks");
      Add(170, "Expression statement failed ");
      Add(171, "Cannot execute default value generator: ");
      Add(172, "Cannot pass constraint: ");
      Add(173, "Column marked as readonly: ");
      Add(174, "Column cannot contain null value: ");
      Add(179, "Operation PutFromFile/GetToFile is not supported for data type: ");
      Add(180, "Cannot access closed table");
      Add(181, "Cannot find column specified by name. Verify the column exists: ");
      Add(182, "Cannot get column by index: ");
      Add(183, "Column value is null: ");
      Add(184, "Identity assigned to the column: ");
      Add(185, "Identity does not exist: ");
      Add(186, "Cannot create identity: ");
      Add(187, "Cannot drop identity: ");
      Add(188, "Seed value cannot be null: ");
      Add(189, "Step value cannot be null: ");
      Add(190, "Invalid step value: ");
      Add(191, "Column data type is not supported by identity: ");
      Add(192, "Default value script has not been assigned to column: ");
      Add(193, "Cannot assign default value script for column: ");
      Add(194, "Cannot drop default value script for column: ");
      Add(195, "Constraint is not existing: ");
      Add(196, "Cannot set constraint: ");
      Add(197, "Cannot delete constraint: ");
      Add(198, "Column data type is not supported by default value script expression: ");
      Add(199, "Primary key is referenced by foreign key constraint: ");
      Add(200, "Cannot set foreign key constraint: ");
      Add(201, "Cannot drop foreign key constraint: ");
      Add(202, "Primary key is not existing in table: ");
      Add(203, "Foreign key cannot relate to primary key in the same table (self reference): ");
      Add(204, "Relationship with same name exists: ");
      Add(205, "Relationship does not exists: ");
      Add(206, "Parent key and child key are identical");
      Add(207, "Cannot alter or drop system column: ");
      Add(208, "Cannot modify table structure or data in the table. The table is used by VistaDB core: ");
      Add(209, "Table is used by sync service and cannot be dropped: ");
      Add(210, "Cannot activate sync service for table: ");
      Add(211, "Cannot deactivate sync service for table: ");
      Add(212, "Cannot apply tombstone table name. The table with same name already exists ");
      Add(213, "Cannot apply name for anchor table. The table with same name already exists ");
      Add(250, "Cannot create row: ");
      Add(251, "Cannot update row: ");
      Add(252, "Cannot delete row: ");
      Add(253, "Cannot activate referential link to: ");
      Add(254, "Cannot create referential link to: ");
      Add(byte.MaxValue, "Cannot create linked referential data: ");
      Add(256, "Cannot update referential link to: ");
      Add(257, "Cannot update referential linked data: ");
      Add(258, "Cannot delete referential link to: ");
      Add(259, "Cannot delete referential linked data: ");
      Add(260, "Trying to update inaccessible row: ");
      Add(261, "Trying to delete inaccessible row: ");
      Add(262, "Row has been modified or deleted by another thread or process");
      Add(270, "Find key procedure cannot be executed");
      Add(271, "Cannot synchronize key position");
      Add(272, "Invalid index to look for key: ");
      Add(280, "The string expression or object name is null reference or empty");
      Add(281, "Cannot compile expression: ");
      Add(282, "Cannot compile index key expression: ");
      Add(285, "Invalid expression: ");
      Add(286, "Parenthesis mismatch");
      Add(287, "Invalid delimiter: ");
      Add(288, "Invalid parameter or parameter type");
      Add(289, "Incorrect operand type or missed parameter or operand in expression: ");
      Add(290, "Cannot match data types in expression or v-function signature");
      Add(291, "Expression should be logical");
      Add(292, "Cannot evaluate operator: ");
      Add(293, "Invalid If-Else group");
      Add(294, "Unexpected Then");
      Add(295, "Unexpected Else");
      Add(296, "String constant has no end delimiter");
      Add(297, "Incomplete expression");
      Add(298, "Invalid operation");
      Add(299, "Invalid float number format: ");
      Add(300, "Value exceeds dynamic range of the data type: ");
      Add(301, "Character column data exceeds maximum length");
      Add(302, "Cannot convert data type: ");
      Add(303, "Data type maximum length should be between 0 and ");
      Add(304, "Invalid page count request to allocate by extended column data: ");
      Add(305, "Cannot initialize sort spool");
      Add(307, "Cannot evaluate index key: ");
      Add(308, "Cannot evaluate expression: ");
      Add(309, "Duplicate key found in index: ");
      Add(320, "Cannot assign environment variable: ");
      Add(321, "Cannot alter relationships in table: ");
      Add(330, "Cannot encrypt node");
      Add(331, "Cannot decrypt node");
      Add(332, "Cannot import data from data storage: ");
      Add(333, "Cannot export data to data storage: ");
      Add(334, "Cannot pack data storage: ");
      Add(335, "Cannot delete all rows in data storage: ");
      Add(336, "Cannot pack database: ");
      Add(337, "Operation cannot be applied in read-only data storage mode: ");
      Add(338, "Operation cannot be applied in shared data storage mode: ");
      Add(339, "Cannot clean up data storage: ");
      Add(340, "Cannot execute script before inserting a new row");
      Add(341, "Cannot execute script after inserting a new row");
      Add(342, "Cannot execute script before updating row");
      Add(343, "Cannot execute script after updating row");
      Add(345, "Cannot execute script after deleting row");
      Add(346, "Cannot initialize free space recycling");
      Add(347, "A database opened via DDA cannot be packed or repaired from a VistaDBConnection. Use DDA operations instead.");
      Add(360, "Cannot export table: ");
      Add(380, "Name of CLR Proc with public static attributes not found: ");
      Add(381, "Duplicate CLR Proc name: ");
      Add(382, "Invalid parameters number passed to invoke CLR Proc");
      Add(383, "The CLR Proc is not registered in database: ");
      Add(384, "The helper FillRow CLR Proc is not registered in database: ");
      Add(385, "The assembly references CLR Proc: ");
      Add(386, "Cannot register CLR Proc");
      Add(387, "Cannot unregister CLR Proc: ");
      Add(388, "Cannot invoke CLR Proc: ");
      Add(389, "The name of assembly is already registered: ");
      Add(390, "The assembly is not registered: ");
      Add(391, "Cannot add assembly: ");
      Add(392, "Cannot update assembly: ");
      Add(393, "Cannot delete assembly: ");
      Add(397, "CLR Trigger not registered");
      Add(394, "Duplicate Clr Trigger name: ");
      Add(395, "Cannot register Clr Trigger");
      Add(396, "Cannot unregister Clr Trigger");
      Add(398, "The assembly references Clr Trigger");
      Add(399, "Cannot set event type for Clr trigger: ");
      Add(400, "Duplicate stored procedure or udf name");
      Add(401, "Cannot register stored procedure or udf");
      Add(402, "Cannot unregister stored procedure or udf");
      Add(450, "Cannot begin transaction");
      Add(452, "Cannot rollback transaction");
      Add(451, "Cannot commit transaction");
      Add(453, "Cannot create transaction log for table: ");
      Add(454, "Cannot open transaction log for table: ");
      Add(455, "Concurrency error. The row is being updated or deleted by another active transaction");
      Add(456, "Isolation level not supported");
      Add(457, "Nested transactions not supported");
      Add(458, "The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION");
      Add(459, "The COMMIT TRANSACTION request has no corresponding BEGIN TRANSACTION");
      Add(460, "TransactionMode is set to OFF on this connection.  No transactions may be used.");
      Add(461, "The encryption key string cannot be an empty string.  Use NULL or Nothing to turn off encryption.");
      Add(462, "TransactionMode can only be set to OFF on this connection.  No transactions may be used.");
      Add(500, "Expected symbol: ");
      Add(501, "Invalid parameter count in function: ");
      Add(502, "Expected expression, but found: ");
      Add(503, "Unterminated string");
      Add(504, "Unterminated table or column name");
      Add(505, "Unterminated column name");
      Add(506, "Unterminated comment");
      Add(507, "Expected expression(s): ");
      Add(550, "Invalid parameter(s) data type in function: ");
      Add(551, "Aggregate function cannot have nested aggregate functions");
      Add(552, "Pattern must be string for: ");
      Add(553, "Invalid pattern. Escape character must be enclosed in the single quotes and have only one symbol");
      Add(554, "Unterminated pattern");
      Add(555, "Invalid pattern. First character in range must be smaller than second");
      Add(556, "Unexpected error: ");
      Add(50000, "Raised error: ");
      Add(660, "Using the statment WITH is unsupported at this location");
      Add(557, "Join condition must have boolean result");
      Add(558, "Invalid operand(s) data type for operator: ");
      Add(559, "LIKE match expression must be string compatible data type");
      Add(560, "Invalid using of IS operator. Expected NULL or NOT NULL, but found: ");
      Add(561, "Invalid expression in the result column: ");
      Add(562, "Columns used in expression with aggregate function is not defined in GROUP BY clause: ");
      Add(563, "Table alias duplicated: ");
      Add(564, "Expected boolean expression");
      Add(565, "WHERE clause cannot have aggregate functions");
      Add(567, "Column does not exist: ");
      Add(568, "Expression already present in GROUP BY clause: ");
      Add(569, "Expression is not present in GROUP BY clause: ");
      Add(570, "HAVING clause must have boolean result");
      Add(571, "HAVING can have only expressions which is in SELECT result or in GROUP BY");
      Add(572, "Table does not exist: ");
      Add(573, "GROUP BY cannot be used if result does not have aggregate functions");
      Add(574, "GROUP BY clause cannot have aggregate functions");
      Add(575, "HAVING clause cannot be used if result does not have aggregate functions");
      Add(576, "Expected keyword: ");
      Add(577, "All SELECTs in union must have the same column count");
      Add(578, "All SELECTs in union must have columns with compatible types");
      Add(579, "In some tables exists the same column: ");
      Add(580, "GROUP BY expression must contain at least one column");
      Add(508, "Unknown data type: ");
      Add(509, "Invalid or incomplete statement: ");
      Add(581, "CASE function must have at least one WHEN operator");
      Add(582, "If in CASE function is not defined input expression, than WHEN expressions must has boolean results");
      Add(583, "In CASE function WHEN expressions must have data type compatible with input expression data type");
      Add(584, "CASE function results must have the same (or compatible) data types");
      Add(585, "Invalid table name: ");
      Add(586, "Invalid column name: ");
      Add(587, "There are fewer columns in the INSERT statement than values specified in the VALUES clause. The number of values in the VALUES clause must match the number of columns specified in the INSERT statement");
      Add(588, "There are more columns in the INSERT statement than values specified in the VALUES clause. The number of values in the VALUES clause must match the number of columns specified in the INSERT statement");
      Add(589, "The select list for the INSERT statement contains more items than the insert list. The number of SELECT values must match the number of INSERT columns");
      Add(590, "The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns");
      Add(591, "Invalid query index: ");
      Add(592, "Invalid token in statement: ");
      Add(593, "Invalid parameters in CREATE DATABASE");
      Add(594, "Column names duplicated in CREATE TABLE: ");
      Add(595, "Constraint names duplicated in CREATE TABLE: ");
      Add(596, "Table can have only one instance of primary key");
      Add(597, "There can be created only one clustered index.  Delete existing clustered index prior to creating another one.");
      Add(598, "Foreign key column count and primary key column count must be the same");
      Add(599, "Column cannot have default value and identity at the same time: ");
      Add(600, "Primary key does not exist in the table: ");
      Add(601, "Invalid Primary key defined in references");
      Add(602, "Column count defined in the view differs from column count defined in the SELECT");
      Add(603, "View name duplicated: ");
      Add(604, "Sub query is read only");
      Add(605, "View is read only: ");
      Add(606, "View does not exist: ");
      Add(607, "Function does not exist: ");
      Add(608, "Invalid identifier: ");
      Add(609, "Stored procedure result set is read only");
      Add(610, "First parameter must have System.Object data type in the FillRow method for CLR Proc: ");
      Add(611, "Expected out parameter for CLR Proc: ");
      Add(612, "FillRow method does not exist for CLR Proc: ");
      Add(613, "Assembly name is not defined for CLR Proc: ");
      Add(614, "Invalid parameter data type in CLR Proc: ");
      Add(615, "CLR Proc execution error: ");
      Add(616, "Parameter not declared: ");
      Add(617, "Name or alias cannot be reserved word: ");
      Add(618, "Expected end of constraint");
      Add(619, "Constraint expression must have boolean result data type");
      Add(620, "Parameter redeclaration: ");
      Add(621, "Invalid parameter name: ");
      Add(622, "Constraint does not exist: ");
      Add(623, "Database not opened");
      Add(624, "Invalid or missing data type specification");
      Add(625, "Data type length is too long. Max length can be: ");
      Add(627, "Invalid schema name. DBO must be used instead of: ");
      Add(628, "Invalid new object name in sp_rename function: ");
      Add(629, "Invalid object type in sp_rename function: ");
      Add(630, "Duplicate specification of the action in the trigger declaration.");
      Add(631, "Value is not a recognized trigger.");
      Add(632, "Incorrect syntax near the keyword");
      Add(634, "Syntax error in the full text search condition");
      Add(635, "Invalid syntax of case function. Searched format is used but non constant expression found.");
      Add(636, "Cannot use a CONTAINS function on table because there is no FullTextSearch index.  Create an FullTextSearch Index on the table first.");
      Add(637, "Only one expression can be specified in the select list");
      Add(638, "Must pass parameter and subsequent parameters as @name = value. After the form @name = value has been used, all subsequent parameters must be passed in the same form.");
      Add(639, "The formal parameter was not declared as an OUTPUT parameter, but the actual parameter passed in requested output. Parameter name:");
      Add(640, "Procedure or function has too many arguments specified. Procedure name:");
      Add(641, "Procedure or Function expects parameter,which was not supplied. Procedure name:");
      Add(642, "A SELECT statement that assigns a value to a variable must not be combined with data-retrieval operations");
      Add(644, "Cannot use a BREAK statement outside the scope of a WHILE statement");
      Add(643, "Cannot use a CONTINUE statement outside the scope of a WHILE statement");
      Add(655, "The ROWGUIDCOL property can only be specified on the uniqueidentifier data type.");
      Add(656, "An aggregate statement using a table must specify a column name.  AggregateFunction(*) is only valid for single table selects.  Qualify a column name with the table such as COUNT(table.column) instead.");
      Add(657, "(ALL *) is not valid syntax with aggregate functions.  Use a column name with the ALL descriptor such as COUNT( ALL ColumnName ) instead.");
      Add(658, "(DISTINCT *) is not valid syntax with aggregate functions.  Use a column name with the descriptor such as COUNT( DISTINCT ColumnName ) instead.");
      Add(661, "A Numeric data type is required in function: ");
      Add(662, "Unable to perform the requested implicit cast operation.  Try CAST() to the desired type instead. Output Target: ");
      Add(663, "Data Conversion failed, unable to convert input to correct datatype. ");
      Add(1001, "VistaDB supports only Text and StoredProcedure command types");
      Add(1002, "Unknown data type: ");
      Add(1003, "VistaDBCommand cannot be executed while associated VistaDBDataReader object opened");
      Add(1004, "VistaDBCommand properties cannot be changed while associated VistaDBDataReader object opened");
      Add(1005, "VistaDBConnection properties cannot be changed while it opened");
      Add(1006, "Name can support as suffix only \"]\"");
      Add(1007, "Name can support as prefix only \"[\"");
      Add(1008, "Command text is empty");
      Add(1009, "Context connection is not available");
      Add(1010, "Schema cannot be generated: ");
      Add(1011, "Connection property must be assigned");
      Add(1012, "Connection must be opened");
      Add(1013, "Only Read Committed Isolation is supported");
      Add(1014, "Keyword not supported");
      Add(2010, "Cannot position to cached row in the table");
      Add(2011, "Last cached row does not exist");
      Add(2012, "New rows were added to the table");
      Add(2013, "Cannot set scope on the table");
      Add(2014, "Cannot reset scope on the table");
      Add(2015, "Cannot set filter on the table");
      Add(2016, "Cached row does not exist");
      Add(2017, "Cannot find needed row");
      Add(2018, "Cannot set active index");
      Add(2019, "Cannot post update");
      Add(2020, "New row does not exist in the current scope");
      Add(2021, "Cannot post insert");
      Add(2022, "Cannot delete row from the table");
      Add(2023, "Cannot open table");
      Add(2040, "Cannot load table schema");
      Add(2041, "Cannot load table data");
      Add(2024, "Cannot reset cache");
    }

        public string GetMessage(int id)
    {
      string str = string.Format("Error {0} (Provider v. {1}): ", id, assemblyVersion);
      if (!ContainsKey(id))
        return str + "unknown error";
      return str + this[id];
    }
  }
}
