





using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace VistaDB
{
  [CompilerGenerated]
  [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
  [DebuggerNonUserCode]
  internal class SQLResource
  {
    private static ResourceManager resourceMan;
    private static CultureInfo resourceCulture;

    internal SQLResource()
    {
    }

    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal static ResourceManager ResourceManager
    {
      get
      {
        if (object.ReferenceEquals((object) SQLResource.resourceMan, (object) null))
          SQLResource.resourceMan = new ResourceManager("VistaDB.SQLResource", typeof (SQLResource).Assembly);
        return SQLResource.resourceMan;
      }
    }

    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal static CultureInfo Culture
    {
      get
      {
        return SQLResource.resourceCulture;
      }
      set
      {
        SQLResource.resourceCulture = value;
      }
    }

    internal static string DataTypes
    {
      get
      {
		return "&lt;?xml version=\"1.0\" standalone=\"yes\"?&gt;& lt; DocumentElement & gt;				&lt; DataTypes & gt;				&lt; TypeName & gt; char&lt;/ TypeName & gt;				&lt; ProviderDbType & gt; 1 & lt;/ ProviderDbType & gt;				&lt; ColumnSize & gt; 8192 & lt;/ ColumnSize & gt;				&lt; CreateParameters & gt; length & lt;/ CreateParameters & gt;				&lt; DataType & gt; System.String & lt;/ DataType & gt;				&lt; CreateFormat & gt; char({ 0})&lt;/ CreateFormat & gt;				&lt; IsAutoIncrementable & gt; false & lt;/ IsAutoIncrementable & gt;				&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;				&lt; IsFixedLength & gt; true & lt;/ IsFixedLength & gt;				&lt; IsFixedPrecisionScale & gt; false & lt;/ IsFixedPrecisionScale & gt;				&lt; IsLong & gt; false & lt;/ IsLong & gt;				&lt; IsNullable & gt; true & lt;/ IsNullable & gt;				&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;				&lt; IsSearchableWithLike & gt; true & lt;/ IsSearchableWithLike & gt;				&lt; IsLiteralsSupported & gt; true & lt;/ IsLiteralsSupported & gt;				&lt; LiteralPrefix & gt; '&lt;/LiteralPrefix&gt;					& lt; LiteralSuffix & gt; '&lt;/LiteralSuffix&gt;						 & lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;				&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;				&lt;/ DataTypes & gt;				&lt; DataTypes & gt;				&lt; TypeName & gt; nchar & lt;/ TypeName & gt;				&lt; ProviderDbType & gt; 2 & lt;/ ProviderDbType & gt;				&lt; ColumnSize & gt; 8192 & lt;/ ColumnSize & gt;				&lt; CreateParameters & gt; length & lt;/ CreateParameters & gt;				&lt; DataType & gt; System.String & lt;/ DataType & gt;				&lt; CreateFormat & gt; nchar({ 0})&lt;/ CreateFormat & gt;				&lt; IsAutoIncrementable & gt; false & lt;/ IsAutoIncrementable & gt;				&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;				&lt; IsFixedLength & gt; true & lt;/ IsFixedLength & gt;				&lt; IsFixedPrecisionScale & gt; false & lt;/ IsFixedPrecisionScale & gt;				&lt; IsLong & gt; false & lt;/ IsLong & gt;				&lt; IsNullable & gt; true & lt;/ IsNullable & gt;				&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;				&lt; IsSearchableWithLike & gt; true & lt;/ IsSearchableWithLike & gt;				&lt; LiteralPrefix & gt; N'&lt;/LiteralPrefix&gt;					& lt; LiteralSuffix & gt; '&lt;/LiteralSuffix&gt;						 & lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;				&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;				&lt;/ DataTypes & gt;				&lt; DataTypes & gt;				&lt; TypeName & gt; varchar & lt;/ TypeName & gt;				&lt; ProviderDbType & gt; 3 & lt;/ ProviderDbType & gt;				&lt; ColumnSize & gt; 8192 & lt;/ ColumnSize & gt;				&lt; CreateParameters & gt; max length&lt;/ CreateParameters & gt;				&lt; DataType & gt; System.String & lt;/ DataType & gt;				&lt; CreateFormat & gt; varchar({ 0})&lt;/ CreateFormat & gt;				&lt; IsAutoIncrementable & gt; false & lt;/ IsAutoIncrementable & gt;				&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;				&lt; IsFixedLength & gt; false & lt;/ IsFixedLength & gt;				&lt; IsFixedPrecisionScale & gt; false & lt;/ IsFixedPrecisionScale & gt;				&lt; IsLong & gt; false & lt;/ IsLong & gt;				&lt; IsNullable & gt; true & lt;/ IsNullable & gt;				&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;				&lt; IsSearchableWithLike & gt; true & lt;/ IsSearchableWithLike & gt;				&lt; LiteralPrefix & gt; '&lt;/LiteralPrefix&gt;					& lt; LiteralSuffix & gt; '&lt;/LiteralSuffix&gt;						 & lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;				&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;				&lt;/ DataTypes & gt;				&lt; DataTypes & gt;				&lt; TypeName & gt; nvarchar & lt;/ TypeName & gt;				&lt; ProviderDbType & gt; 4 & lt;/ ProviderDbType & gt;				&lt; ColumnSize & gt; 8192 & lt;/ ColumnSize & gt;				&lt; CreateParameters & gt; max length&lt;/ CreateParameters & gt;				&lt; DataType & gt; System.String & lt;/ DataType & gt;				&lt; CreateFormat & gt; nvarchar({ 0})&lt;/ CreateFormat & gt;				&lt; IsAutoIncrementable & gt; false & lt;/ IsAutoIncrementable & gt;				&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;				&lt; IsFixedLength & gt; false & lt;/ IsFixedLength & gt;				&lt; IsFixedPrecisionScale & gt; false & lt;/ IsFixedPrecisionScale & gt;				&lt; IsLong & gt; false & lt;/ IsLong & gt;				&lt; IsNullable & gt; true & lt;/ IsNullable & gt;				&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;				&lt; IsSearchableWithLike & gt; true & lt;/ IsSearchableWithLike & gt;				&lt; LiteralPrefix & gt; N'&lt;/LiteralPrefix&gt;					& lt; LiteralSuffix & gt; '&lt;/LiteralSuffix&gt;						 & lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;				&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;				&lt;/ DataTypes & gt;				&lt; DataTypes & gt;				&lt; TypeName & gt; text & lt;/ TypeName & gt;				&lt; ProviderDbType & gt; 5 & lt;/ ProviderDbType & gt;				&lt; ColumnSize & gt; 2147483647 & lt;/ ColumnSize & gt;				&lt; DataType & gt; System.String & lt;/ DataType & gt;				&lt; CreateFormat & gt; text & lt;/ CreateFormat & gt;				&lt; IsAutoIncrementable & gt; false & lt;/ IsAutoIncrementable & gt;				&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;				&lt; IsFixedLength & gt; false & lt;/ IsFixedLength & gt;				&lt; IsFixedPrecisionScale & gt; false & lt;/ IsFixedPrecisionScale & gt;				&lt; IsLong & gt; true & lt;/ IsLong & gt;				&lt; IsNullable & gt; true & lt;/ IsNullable & gt;				&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;				&lt; IsSearchableWithLike & gt; true & lt;/ IsSearchableWithLike & gt;				&lt; LiteralPrefix & gt; '&lt;/LiteralPrefix&gt;					& lt; LiteralSuffix & gt; '&lt;/LiteralSuffix&gt;						 & lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;				&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;				&lt;/ DataTypes & gt;				&lt; DataTypes & gt;				&lt; TypeName & gt; ntext & lt;/ TypeName & gt;				&lt; ProviderDbType & gt; 6 & lt;/ ProviderDbType & gt;				&lt; ColumnSize & gt; 1073741823 & lt;/ ColumnSize & gt;				&lt; DataType & gt; System.String & lt;/ DataType & gt;				&lt; CreateFormat & gt; ntext & lt;/ CreateFormat & gt;				&lt; IsAutoIncrementable & gt; false & lt;/ IsAutoIncrementable & gt;				&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;				&lt; IsFixedLength & gt; false & lt;/ IsFixedLength & gt;				&lt; IsFixedPrecisionScale & gt; false & lt;/ IsFixedPrecisionScale & gt;				&lt; IsLong & gt; true & lt;/ IsLong & gt;				&lt; IsNullable & gt; true & lt;/ IsNullable & gt;				&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;				&lt; IsSearchableWithLike & gt; true & lt;/ IsSearchableWithLike & gt;				&lt; LiteralPrefix & gt; N'&lt;/LiteralPrefix&gt;					& lt; LiteralSuffix & gt; '&lt;/LiteralSuffix&gt;						 & lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;				&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;				&lt;/ DataTypes & gt;				&lt; DataTypes & gt;				&lt; TypeName & gt; TinyInt & lt;/ TypeName & gt;				&lt; ProviderDbType & gt; 8 & lt;/ ProviderDbType & gt;				&lt; ColumnSize & gt; 1 & lt;/ ColumnSize & gt;				&lt; DataType & gt; System.Byte & lt;/ DataType & gt;				&lt; CreateFormat & gt; TinyInt & lt;/ CreateFormat & gt;				&lt; IsAutoIncrementable & gt; true & lt;/ IsAutoIncrementable & gt;				&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;				&lt; IsFixedLength & gt; true & lt;/ IsFixedLength & gt;				&lt; IsFixedPrecisionScale & gt; true & lt;/ IsFixedPrecisionScale & gt;				&lt; IsLong & gt; false & lt;/ IsLong & gt;				&lt; IsNullable & gt; true & lt;/ IsNullable & gt;				&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;				&lt; IsSearchableWithLike & gt; false & lt;/ IsSearchableWithLike & gt;				&lt; IsUnsigned & gt; true & lt;/ IsUnsigned & gt;				&lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;				&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;				&lt;/ DataTypes & gt;				&lt; DataTypes & gt;				&lt; TypeName & gt; SmallInt & lt;/ TypeName & gt;				&lt; ProviderDbType & gt; 9 & lt;/ ProviderDbType & gt;				&lt; ColumnSize & gt; 2 & lt;/ ColumnSize & gt;				&lt; DataType & gt; System.Int16 & lt;/ DataType & gt;				&lt; CreateFormat & gt; SmallInt & lt;/ CreateFormat & gt;				&lt; IsAutoIncrementable & gt; true & lt;/ IsAutoIncrementable & gt;				&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;				&lt; IsFixedLength & gt; true & lt;/ IsFixedLength & gt;				&lt; IsFixedPrecisionScale & gt; true & lt;/ IsFixedPrecisionScale & gt;				&lt; IsLong & gt; false & lt;/ IsLong & gt;				&lt; IsNullable & gt; true & lt;/ IsNullable & gt;				&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;				&lt; IsSearchableWithLike & gt; false & lt;/ IsSearchableWithLike & gt;				&lt; IsUnsigned & gt; false & lt;/ IsUnsigned & gt;				&lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;				&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;				&lt;/ DataTypes & gt;				&lt; DataTypes & gt;				&lt; TypeName & gt; Int & lt;/ TypeName & gt;				&lt; ProviderDbType & gt; 10 & lt;/ ProviderDbType & gt;				&lt; ColumnSize & gt; 4 & lt;/ ColumnSize & gt;				&lt; DataType & gt; System.Int32 & lt;/ DataType & gt;				&lt; CreateFormat & gt; Int & lt;/ CreateFormat & gt;				&lt; IsAutoIncrementable & gt; true & lt;/ IsAutoIncrementable & gt;				&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;				&lt; IsFixedLength & gt; true & lt;/ IsFixedLength & gt;				&lt; IsFixedPrecisionScale & gt; true & lt;/ IsFixedPrecisionScale & gt;				&lt; IsLong & gt; false & lt;/ IsLong & gt;				&lt; IsNullable & gt; true & lt;/ IsNullable & gt;				&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;				&lt; IsSearchableWithLike & gt; false & lt;/ IsSearchableWithLike & gt;				&lt; IsUnsigned & gt; false & lt;/ IsUnsigned & gt;				&lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;				&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;				&lt;/ DataTypes & gt;				&lt; DataTypes & gt;				&lt; TypeName & gt; BigInt & lt;/ TypeName & gt;				&lt; ProviderDbType & gt; 11 & lt;/ ProviderDbType & gt;				&lt; ColumnSize & gt; 19 & lt;/ ColumnSize & gt;				&lt; CreateFormat & gt; BigInt & lt;/ CreateFormat & gt;				&lt; DataType & gt; System.Int64 & lt;/ DataType & gt;				&lt; IsAutoIncrementable & gt; true & lt;/ IsAutoIncrementable & gt;				&lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;				&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;				&lt; IsFixedLength & gt; true & lt;/ IsFixedLength & gt;				&lt; IsFixedPrecisionScale & gt; true & lt;/ IsFixedPrecisionScale & gt;				&lt; IsLong & gt; false & lt;/ IsLong & gt;				&lt; IsNullable & gt; true & lt;/ IsNullable & gt;				&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;				&lt; IsSearchableWithLike & gt; false & lt;/ IsSearchableWithLike & gt;				&lt; IsUnsigned & gt; false & lt;/ IsUnsigned & gt;				&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;				&lt;/ DataTypes & gt;				&lt; DataTypes & gt;				&lt; TypeName & gt; Real & lt;/ TypeName & gt;				&lt; ProviderDbType & gt; 12 & lt;/ ProviderDbType & gt;				&lt; ColumnSize & gt; 4 & lt;/ ColumnSize & gt;				&lt; DataType & gt; System.Single & lt;/ DataType & gt;				&lt; CreateFormat & gt; Real & lt;/ CreateFormat & gt;				&lt; IsAutoIncrementable & gt; false & lt;/ IsAutoIncrementable & gt;				&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;				&lt; IsFixedLength & gt; true & lt;/ IsFixedLength & gt;				&lt; IsFixedPrecisionScale & gt; false & lt;/ IsFixedPrecisionScale & gt;				&lt; IsLong & gt; false & lt;/ IsLong & gt;				&lt; IsNullable & gt; true & lt;/ IsNullable & gt;				&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;				&lt; IsSearchableWithLike & gt; false & lt;/ IsSearchableWithLike & gt;				&lt; IsUnsigned & gt; false & lt;/ IsUnsigned & gt;				&lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;				&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;				&lt;/ DataTypes & gt;				&lt; DataTypes & gt;				&lt; TypeName & gt; Float & lt;/ TypeName & gt;				&lt; ProviderDbType & gt; 13 & lt;/ ProviderDbType & gt;				&lt; ColumnSize & gt; 8 & lt;/ ColumnSize & gt;				&lt; DataType & gt; System.Double & lt;/ DataType & gt;				&lt; CreateFormat & gt; float({ 0})&lt;/ CreateFormat & gt;				&lt; CreateParameters & gt; bits used to store the mantissa&lt;/ CreateParameters & gt;				&lt; IsAutoIncrementable & gt; false & lt;/ IsAutoIncrementable & gt;				&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;				&lt; IsFixedLength & gt; true & lt;/ IsFixedLength & gt;				&lt; IsFixedPrecisionScale & gt; false & lt;/ IsFixedPrecisionScale & gt;				&lt; IsLong & gt; false & lt;/ IsLong & gt;				&lt; IsNullable & gt; true & lt;/ IsNullable & gt;				&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;				&lt; IsSearchableWithLike & gt; false & lt;/ IsSearchableWithLike & gt;				&lt; IsUnsigned & gt; false & lt;/ IsUnsigned & gt;				&lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;				&lt; IsLiteralsSupported & gt; false & lt;/ IsLiteralsSupported & gt;				&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;				&lt;/ DataTypes & gt;				&lt; DataTypes & gt;				&lt; TypeName & gt; Decimal & lt;/ TypeName & gt;				&lt; ProviderDbType & gt; 14 & lt;/ ProviderDbType & gt;				&lt; ColumnSize & gt; 12 & lt;/ ColumnSize & gt;				&lt; DataType & gt; System.Decimal & lt;/ DataType & gt;				&lt; CreateFormat & gt; decimal({ 0}, { 1})&lt;/ CreateFormat & gt;				&lt; CreateParameters & gt; precision, scale & lt;/ CreateParameters & gt;				&lt; IsAutoIncrementable & gt; true & lt;/ IsAutoIncrementable & gt;				&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;				&lt; IsFixedLength & gt; true & lt;/ IsFixedLength & gt;				&lt; IsFixedPrecisionScale & gt; false & lt;/ IsFixedPrecisionScale & gt;				&lt; IsLong & gt; false & lt;/ IsLong & gt;				&lt; IsNullable & gt; true & lt;/ IsNullable & gt;				&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;				&lt; IsSearchableWithLike & gt; false & lt;/ IsSearchableWithLike & gt;				&lt; IsUnsigned & gt; false & lt;/ IsUnsigned & gt;				&lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;				&lt; IsLiteralsSupported & gt; false & lt;/ IsLiteralsSupported & gt;				&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;				&lt; MaximumScale & gt; 38 & lt;/ MaximumScale & gt;				&lt; MinimumScale & gt; 0 & lt;/ MinimumScale & gt;				&lt;/ DataTypes & gt;				&lt; DataTypes & gt;				&lt; TypeName & gt; Money & lt;/ TypeName & gt;				&lt; ProviderDbType & gt; 15 & lt;/ ProviderDbType & gt;				&lt; ColumnSize & gt; 8 & lt;/ ColumnSize & gt;				&lt; DataType & gt; System.Decimal & lt;/ DataType & gt;				&lt; CreateFormat & gt; Money & lt;/ CreateFormat & gt;				&lt; IsAutoIncrementable & gt; false & lt;/ IsAutoIncrementable & gt;				&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;				&lt; IsFixedLength & gt; true & lt;/ IsFixedLength & gt;				&lt; IsFixedPrecisionScale & gt; true & lt;/ IsFixedPrecisionScale & gt;				&lt; IsLong & gt; false & lt;/ IsLong & gt;				&lt; IsNullable & gt; true & lt;/ IsNullable & gt;				&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;				&lt; IsSearchableWithLike & gt; false & lt;/ IsSearchableWithLike & gt;				&lt; IsUnsigned & gt; false & lt;/ IsUnsigned & gt;				&lt; IsBestMatch & gt; false & lt;/ IsBestMatch & gt;				&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;				&lt;/ DataTypes & gt;				&lt; DataTypes & gt;				&lt; TypeName & gt; SmallMoney & lt;/ TypeName & gt;				&lt; ProviderDbType & gt; 16 & lt;/ ProviderDbType & gt;				&lt; ColumnSize & gt; 4 & lt;/ ColumnSize & gt;				&lt; DataType & gt; System.Decimal & lt;/ DataType & gt;				&lt; CreateFormat & gt; SmallMoney & lt;/ CreateFormat & gt;				&lt; IsAutoIncrementable & gt; false & lt;/ IsAutoIncrementable & gt;				&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;				&lt; IsFixedLength & gt; true & lt;/ IsFixedLength & gt;				&lt; IsFixedPrecisionScale & gt; true & lt;/ IsFixedPrecisionScale & gt;				&lt; IsLong & gt; false & lt;/ IsLong & gt;				&lt; IsNullable & gt; true & lt;/ IsNullable & gt;				&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;				&lt; IsSearchableWithLike & gt; false & lt;/ IsSearchableWithLike & gt;				&lt; IsUnsigned & gt; false & lt;/ IsUnsigned & gt;				&lt; IsBestMatch & gt; false & lt;/ IsBestMatch & gt;				&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;				&lt;/ DataTypes & gt;				&lt; DataTypes & gt;				&lt; TypeName & gt; Bit & lt;/ TypeName & gt;				&lt; ProviderDbType & gt; 17 & lt;/ ProviderDbType & gt;				&lt; ColumnSize & gt; 1 & lt;/ ColumnSize & gt;				&lt; DataType & gt; System.Boolean & lt;/ DataType & gt;				&lt; CreateFormat & gt; Bit & lt;/ CreateFormat & gt;				&lt; IsAutoIncrementable & gt; false & lt;/ IsAutoIncrementable & gt;				&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;				&lt; IsFixedLength & gt; true & lt;/ IsFixedLength & gt;				&lt; IsFixedPrecisionScale & gt; false & lt;/ IsFixedPrecisionScale & gt;				&lt; IsLong & gt; false & lt;/ IsLong & gt;				&lt; IsNullable & gt; true & lt;/ IsNullable & gt;				&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;				&lt; IsSearchableWithLike & gt; false & lt;/ IsSearchableWithLike & gt;				&lt; IsBestMatch & gt; false & lt;/ IsBestMatch & gt;				&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;				&lt;/ DataTypes & gt;				&lt; DataTypes & gt;				&lt; TypeName & gt; SmallDateTime & lt;/ TypeName & gt;				&lt; ProviderDbType & gt; 23 & lt;/ ProviderDbType & gt;				&lt; ColumnSize & gt; 8 & lt;/ ColumnSize & gt;				&lt; DataType & gt; System.DateTime & lt;/ DataType & gt;				&lt; CreateFormat & gt; SmallDateTime & lt;/ CreateFormat & gt;				&lt; IsAutoIncrementable & gt; false & lt;/ IsAutoIncrementable & gt;				&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;				&lt; IsFixedLength & gt; true & lt;/ IsFixedLength & gt;				&lt; IsFixedPrecisionScale & gt; false & lt;/ IsFixedPrecisionScale & gt;				&lt; IsLong & gt; false & lt;/ IsLong & gt;				&lt; IsNullable & gt; true & lt;/ IsNullable & gt;				&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;				&lt; IsSearchableWithLike & gt; true & lt;/ IsSearchableWithLike & gt;				&lt; LiteralPrefix & gt;				{ ts'&lt;/LiteralPrefix&gt;& lt; LiteralSuffix & gt; '}&lt;/LiteralSuffix&gt; & lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;					&lt; IsLiteralsSupported & gt; false & lt;/ IsLiteralsSupported & gt;					&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;					&lt;/ DataTypes & gt;					&lt; DataTypes & gt;					&lt; TypeName & gt; DateTime & lt;/ TypeName & gt;					&lt; ProviderDbType & gt; 19 & lt;/ ProviderDbType & gt;					&lt; ColumnSize & gt; 8 & lt;/ ColumnSize & gt;					&lt; DataType & gt; System.DateTime & lt;/ DataType & gt;					&lt; CreateFormat & gt; DateTime & lt;/ CreateFormat & gt;					&lt; IsAutoIncrementable & gt; false & lt;/ IsAutoIncrementable & gt;					&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;					&lt; IsFixedLength & gt; true & lt;/ IsFixedLength & gt;					&lt; IsFixedPrecisionScale & gt; false & lt;/ IsFixedPrecisionScale & gt;					&lt; IsLong & gt; false & lt;/ IsLong & gt;					&lt; IsNullable & gt; true & lt;/ IsNullable & gt;					&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;					&lt; IsSearchableWithLike & gt; true & lt;/ IsSearchableWithLike & gt;					&lt; LiteralPrefix & gt;					{ ts'&lt;/LiteralPrefix&gt;& lt; LiteralSuffix & gt; '}&lt;/LiteralSuffix&gt;	 & lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;						&lt; IsLiteralsSupported & gt; false & lt;/ IsLiteralsSupported & gt;						&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;						&lt;/ DataTypes & gt;						&lt; DataTypes & gt;						&lt; TypeName & gt; Image & lt;/ TypeName & gt;						&lt; ProviderDbType & gt; 20 & lt;/ ProviderDbType & gt;						&lt; ColumnSize & gt; 2147483647 & lt;/ ColumnSize & gt;						&lt; DataType & gt; System.Byte[]&lt;/ DataType & gt;						&lt; CreateFormat & gt; Image & lt;/ CreateFormat & gt;						&lt; IsAutoIncrementable & gt; false & lt;/ IsAutoIncrementable & gt;						&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;						&lt; IsFixedLength & gt; false & lt;/ IsFixedLength & gt;						&lt; IsFixedPrecisionScale & gt; false & lt;/ IsFixedPrecisionScale & gt;						&lt; IsLong & gt; true & lt;/ IsLong & gt;						&lt; IsNullable & gt; true & lt;/ IsNullable & gt;						&lt; IsSearchable & gt; false & lt;/ IsSearchable & gt;						&lt; IsSearchableWithLike & gt; false & lt;/ IsSearchableWithLike & gt;						&lt; LiteralPrefix & gt; 0x & lt;/ LiteralPrefix & gt;						&lt; LiteralSuffix & gt; &lt;/ LiteralSuffix & gt;						&lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;						&lt; IsLiteralsSupported & gt; false & lt;/ IsLiteralsSupported & gt;						&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;						&lt;/ DataTypes & gt;						&lt; DataTypes & gt;						&lt; TypeName & gt; VarBinary & lt;/ TypeName & gt;						&lt; ProviderDbType & gt; 21 & lt;/ ProviderDbType & gt;						&lt; ColumnSize & gt; 65536 & lt;/ ColumnSize & gt;						&lt; DataType & gt; System.Byte[]&lt;/ DataType & gt;						&lt; CreateFormat & gt; varbinary({ 0})&lt;/ CreateFormat & gt;						&lt; CreateParameters & gt; max length&lt;/ CreateParameters & gt;						&lt; IsAutoIncrementable & gt; false & lt;/ IsAutoIncrementable & gt;						&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;						&lt; IsFixedLength & gt; false & lt;/ IsFixedLength & gt;						&lt; IsFixedPrecisionScale & gt; false & lt;/ IsFixedPrecisionScale & gt;						&lt; IsLong & gt; false & lt;/ IsLong & gt;						&lt; IsNullable & gt; true & lt;/ IsNullable & gt;						&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;						&lt; IsSearchableWithLike & gt; false & lt;/ IsSearchableWithLike & gt;						&lt; LiteralPrefix & gt; 0x & lt;/ LiteralPrefix & gt;						&lt; LiteralSuffix & gt; &lt;/ LiteralSuffix & gt;						&lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;						&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;						&lt;/ DataTypes & gt;						&lt; DataTypes & gt;						&lt; TypeName & gt; UniqueIdentifier & lt;/ TypeName & gt;						&lt; ProviderDbType & gt; 22 & lt;/ ProviderDbType & gt;						&lt; ColumnSize & gt; 16 & lt;/ ColumnSize & gt;						&lt; DataType & gt; System.Guid & lt;/ DataType & gt;						&lt; CreateFormat & gt; UniqueIdentifier & lt;/ CreateFormat & gt;						&lt; IsAutoIncrementable & gt; false & lt;/ IsAutoIncrementable & gt;						&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;						&lt; IsFixedLength & gt; true & lt;/ IsFixedLength & gt;						&lt; IsFixedPrecisionScale & gt; true & lt;/ IsFixedPrecisionScale & gt;						&lt; IsLong & gt; false & lt;/ IsLong & gt;						&lt; IsNullable & gt; true & lt;/ IsNullable & gt;						&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;						&lt; IsSearchableWithLike & gt; false & lt;/ IsSearchableWithLike & gt;						&lt; LiteralPrefix & gt; '&lt;/LiteralPrefix&gt;							& lt; LiteralSuffix & gt; '&lt;/LiteralSuffix&gt;								 & lt; IsBestMatch & gt; true & lt;/ IsBestMatch & gt;						&lt; IsConcurrencyType & gt; false & lt;/ IsConcurrencyType & gt;						&lt;/ DataTypes & gt;						&lt; DataTypes & gt;						&lt; TypeName & gt; Timestamp & lt;/ TypeName & gt;						&lt; ProviderDbType & gt; 24 & lt;/ ProviderDbType & gt;						&lt; ColumnSize & gt; 8 & lt;/ ColumnSize & gt;						&lt; DataType & gt; System.Int64 & lt;/ DataType & gt;						&lt; CreateFormat & gt; Timestamp & lt;/ CreateFormat & gt;						&lt; IsAutoIncrementable & gt; true & lt;/ IsAutoIncrementable & gt;						&lt; IsCaseSensitive & gt; false & lt;/ IsCaseSensitive & gt;						&lt; IsFixedLength & gt; true & lt;/ IsFixedLength & gt;						&lt; IsFixedPrecisionScale & gt; true & lt;/ IsFixedPrecisionScale & gt;						&lt; IsLong & gt; false & lt;/ IsLong & gt;						&lt; IsNullable & gt; false & lt;/ IsNullable & gt;						&lt; IsSearchable & gt; true & lt;/ IsSearchable & gt;						&lt; IsSearchableWithLike & gt; false & lt;/ IsSearchableWithLike & gt;						&lt; IsUnsigned & gt; false & lt;/ IsUnsigned & gt;						&lt; IsBestMatch & gt; false & lt;/ IsBestMatch & gt;						&lt; IsLiteralsSupported & gt; false & lt;/ IsLiteralsSupported & gt;						&lt; IsConcurrencyType & gt; true & lt;/ IsConcurrencyType & gt;						&lt;/ DataTypes & gt;						&lt;/ DocumentElement & gt; ";
        //return SQLResource.ResourceManager.GetString(nameof (DataTypes), SQLResource.resourceCulture);
      }
    }

    internal static string MetaDataCollections
    {
      get
      {
		return "&lt;?xml version=\"1.0\" encoding=\"utf - 8\" ?&gt;  & lt; DocumentElement & gt;				&lt; MetaDataCollections & gt;				&lt; CollectionName & gt; MetaDataCollections & lt;/ CollectionName & gt;				&lt; NumberOfRestrictions & gt; 0 & lt;/ NumberOfRestrictions & gt;				&lt; NumberOfIdentifierParts & gt; 0 & lt;/ NumberOfIdentifierParts & gt;				&lt;/ MetaDataCollections & gt;				&lt; MetaDataCollections & gt;				&lt; CollectionName & gt; DataSourceInformation & lt;/ CollectionName & gt;				&lt; NumberOfRestrictions & gt; 0 & lt;/ NumberOfRestrictions & gt;				&lt; NumberOfIdentifierParts & gt; 0 & lt;/ NumberOfIdentifierParts & gt;				&lt;/ MetaDataCollections & gt;				&lt; MetaDataCollections & gt;				&lt; CollectionName & gt; DataTypes & lt;/ CollectionName & gt;				&lt; NumberOfRestrictions & gt; 0 & lt;/ NumberOfRestrictions & gt;				&lt; NumberOfIdentifierParts & gt; 0 & lt;/ NumberOfIdentifierParts & gt;				&lt;/ MetaDataCollections & gt;				&lt; MetaDataCollections & gt;				&lt; CollectionName & gt; Columns & lt;/ CollectionName & gt;				&lt; NumberOfRestrictions & gt; 4 & lt;/ NumberOfRestrictions & gt;				&lt; NumberOfIdentifierParts & gt; 4 & lt;/ NumberOfIdentifierParts & gt;				&lt;/ MetaDataCollections & gt;				&lt; MetaDataCollections & gt;				&lt; CollectionName & gt; Indexes & lt;/ CollectionName & gt;				&lt; NumberOfRestrictions & gt; 4 & lt;/ NumberOfRestrictions & gt;				&lt; NumberOfIdentifierParts & gt; 3 & lt;/ NumberOfIdentifierParts & gt;				&lt;/ MetaDataCollections & gt;				&lt; MetaDataCollections & gt;				&lt; CollectionName & gt; IndexColumns & lt;/ CollectionName & gt;				&lt; NumberOfRestrictions & gt; 5 & lt;/ NumberOfRestrictions & gt;				&lt; NumberOfIdentifierParts & gt; 4 & lt;/ NumberOfIdentifierParts & gt;				&lt;/ MetaDataCollections & gt;				&lt; MetaDataCollections & gt;				&lt; CollectionName & gt; Tables & lt;/ CollectionName & gt;				&lt; NumberOfRestrictions & gt; 4 & lt;/ NumberOfRestrictions & gt;				&lt; NumberOfIdentifierParts & gt; 3 & lt;/ NumberOfIdentifierParts & gt;				&lt;/ MetaDataCollections & gt;				&lt; MetaDataCollections & gt;				&lt; CollectionName & gt; ForeignKeys & lt;/ CollectionName & gt;				&lt; NumberOfRestrictions & gt; 4 & lt;/ NumberOfRestrictions & gt;				&lt; NumberOfIdentifierParts & gt; 3 & lt;/ NumberOfIdentifierParts & gt;				&lt;/ MetaDataCollections & gt;				&lt; MetaDataCollections & gt;				&lt; CollectionName & gt; ForeignKeyColumns & lt;/ CollectionName & gt;				&lt; NumberOfRestrictions & gt; 5 & lt;/ NumberOfRestrictions & gt;				&lt; NumberOfIdentifierParts & gt; 4 & lt;/ NumberOfIdentifierParts & gt;				&lt;/ MetaDataCollections & gt;				&lt; MetaDataCollections & gt;				&lt; CollectionName & gt; ReservedWords & lt;/ CollectionName & gt;				&lt; NumberOfRestrictions & gt; 0 & lt;/ NumberOfRestrictions & gt;				&lt; NumberOfIdentifierParts & gt; 0 & lt;/ NumberOfIdentifierParts & gt;				&lt;/ MetaDataCollections & gt;				&lt; MetaDataCollections & gt;				&lt; CollectionName & gt; Views & lt;/ CollectionName & gt;				&lt; NumberOfRestrictions & gt; 3 & lt;/ NumberOfRestrictions & gt;				&lt; NumberOfIdentifierParts & gt; 3 & lt;/ NumberOfIdentifierParts & gt;				&lt;/ MetaDataCollections & gt;				&lt; MetaDataCollections & gt;				&lt; CollectionName & gt; ViewColumns & lt;/ CollectionName & gt;				&lt; NumberOfRestrictions & gt; 4 & lt;/ NumberOfRestrictions & gt;				&lt; NumberOfIdentifierParts & gt; 4 & lt;/ NumberOfIdentifierParts & gt;				&lt;/ MetaDataCollections & gt;				&lt; MetaDataCollections & gt;				&lt; CollectionName & gt; Restrictions & lt;/ CollectionName & gt;				&lt; NumberOfRestrictions & gt; 0 & lt;/ NumberOfRestrictions & gt;				&lt; NumberOfIdentifierParts & gt; 0 & lt;/ NumberOfIdentifierParts & gt;				&lt;/ MetaDataCollections & gt;				&lt;/ DocumentElement & gt; ";
        //return SQLResource.ResourceManager.GetString(nameof (MetaDataCollections), SQLResource.resourceCulture);
      }
    }

    internal static string ReservedWords_VDB4
    {
      get
      {
				return @"ADD
ALL
ALTER
AND
ANY
AS
ASC
AUTHORIZATION
BACKUP
BEGIN
BETWEEN
BREAK
BROWSE
BULK
BY
CASCADE
CASE
CHECK
CHECKPOINT
CLOSE
CLUSTERED
COALESCE
COLLATE
COLUMN
COMMIT
COMPUTE
CONSTRAINT
CONTAINS
CONTAINSTABLE
CONTINUE
CONVERT
CREATE
CROSS
CURRENT
CURRENT_DATE
CURRENT_TIME
CURRENT_TIMESTAMP
CURRENT_USER
CURSOR
DATABASE
DATETIME2
DATETIMEOFFSET
DBCC
DEALLOCATE
DECLARE
DEFAULT
DELETE
DENY
DESC
DISK
DISTINCT
DISTRIBUTED
DOUBLE
DROP
DUMP
ELSE
END
ERRLVL
ESCAPE
EXCEPT
EXEC
EXECUTE
EXISTS
EXIT
EXTERNAL
FETCH
FILE
FILLFACTOR
FOR
FOREIGN
FREETEXT
FREETEXTTABLE
FROM
FULL
FUNCTION
GOTO
GRANT
GROUP
HAVING
HOLDLOCK
IDENT_SEED
IDENT_CURRENT
IDENTITY
IDENTITY_INSERT
IDENTITYCOL
IF
IMAGE
IN
INDEX
INNER
INSERT
INTERSECT
INTO
IS
ISDATE
ISNULL
ISNUMERIC
JOIN
KEY
KILL
LEFT
LIKE
LINENO
LOAD
NATIONAL
NEWSEQUENTIALID
NOCHECK
NONCLUSTERED
NOT
NULL
NULLIF
OBJECT_DEFINITION
OBJECT_ID
OBJECT_NAME
OBJECT_SCHEMA_NAME
OBJECTPROPERTY
OBJECTPROPERTYEX
OF
OFF
OFFSETS
ON
OPEN
OPENDATASOURCE
OPENQUERY
OPENROWSET
OPENXML
OPTION
OR
ORDER
OUTER
OVER
PERCENT
PIVOT
PLAN
PRECISION
PRIMARY
PRINT
PROC
PROCEDURE
PUBLIC
RAISERROR
READ
READTEXT
RECONFIGURE
REFERENCES
REPLICATION
RESTORE
RESTRICT
RETURN
REVERT
REVERSE
REVOKE
RIGHT
ROLLBACK
ROUND
ROWCOUNT
ROWGUIDCOL
ROWVERSION
RULE
SAVE
SCHEMA
SCHEMA_ID
SCHEMA_NAME
SCOPE_IDENTITY
SECURITYAUDIT
SELECT
SESSION_USER
SET
SETUSER
SHUTDOWN
SIGN
SIN
SKIP
SMALLDATETIME
SOME
STATISTICS
SYSTEM_USER
SQL_VARIANT
SWITCHOFFSET
TABLE
TABLESAMPLE
TEXTSIZE
TIES
TIME
TIMESTAMP
TIMEZONE
THEN
TO
TODATETIMEOFFSET
TOP
TRAN
TRANCOUNT
TRANSACTION
TRIGGER
TRUNCATE
TSEQUAL
UNION
UNIQUE
UNIQUEIDENTIFIER
UNPIVOT
UPDATE
UPDATETEXT
USE
USER
VALUES
VARYING
VIEW
WAITFOR
WHEN
WHERE
WHILE
WITH
WRITETEXT
XML
XML_SCHEMA_NAMESPACE
YEAR";
        //return SQLResource.ResourceManager.GetString(nameof (ReservedWords_VDB4), SQLResource.resourceCulture);
      }
    }

    internal static string Restrictions
    {
      get
      {
		return "&lt;?xml version=\"1.0\" encoding=\"utf - 8\" ?&gt;  & lt; DocumentElement & gt;				&lt; Restrictions & gt;				&lt; CollectionName & gt; Columns & lt;/ CollectionName & gt;				&lt; RestrictionName & gt; Table & lt;/ RestrictionName & gt;				&lt; RestrictionNumber & gt; 3 & lt;/ RestrictionNumber & gt;				&lt;/ Restrictions & gt;				&lt; Restrictions & gt;				&lt; CollectionName & gt; Columns & lt;/ CollectionName & gt;				&lt; RestrictionName & gt; Column & lt;/ RestrictionName & gt;				&lt; RestrictionNumber & gt; 4 & lt;/ RestrictionNumber & gt;				&lt;/ Restrictions & gt;				&lt; Restrictions & gt;				&lt; CollectionName & gt; Indexes & lt;/ CollectionName & gt;				&lt; RestrictionName & gt; Table & lt;/ RestrictionName & gt;				&lt; RestrictionNumber & gt; 3 & lt;/ RestrictionNumber & gt;				&lt;/ Restrictions & gt;				&lt; Restrictions & gt;				&lt; CollectionName & gt; Indexes & lt;/ CollectionName & gt;				&lt; RestrictionName & gt; Name & lt;/ RestrictionName & gt;				&lt; RestrictionNumber & gt; 4 & lt;/ RestrictionNumber & gt;				&lt;/ Restrictions & gt;				&lt; Restrictions & gt;				&lt; CollectionName & gt; IndexColumns & lt;/ CollectionName & gt;				&lt; RestrictionName & gt; Table & lt;/ RestrictionName & gt;				&lt; RestrictionNumber & gt; 3 & lt;/ RestrictionNumber & gt;				&lt;/ Restrictions & gt;				&lt; Restrictions & gt;				&lt; CollectionName & gt; IndexColumns & lt;/ CollectionName & gt;				&lt; RestrictionName & gt; ConstraintName & lt;/ RestrictionName & gt;				&lt; RestrictionNumber & gt; 4 & lt;/ RestrictionNumber & gt;				&lt;/ Restrictions & gt;				&lt; Restrictions & gt;				&lt; CollectionName & gt; IndexColumns & lt;/ CollectionName & gt;				&lt; RestrictionName & gt; Column & lt;/ RestrictionName & gt;				&lt; RestrictionNumber & gt; 5 & lt;/ RestrictionNumber & gt;				&lt;/ Restrictions & gt;				&lt; Restrictions & gt;				&lt; CollectionName & gt; Tables & lt;/ CollectionName & gt;				&lt; RestrictionName & gt; Table & lt;/ RestrictionName & gt;				&lt; RestrictionNumber & gt; 3 & lt;/ RestrictionNumber & gt;				&lt;/ Restrictions & gt;				&lt; Restrictions & gt;				&lt; CollectionName & gt; Tables & lt;/ CollectionName & gt;				&lt; RestrictionName & gt; TableType & lt;/ RestrictionName & gt;				&lt; RestrictionNumber & gt; 4 & lt;/ RestrictionNumber & gt;				&lt;/ Restrictions & gt;				&lt; Restrictions & gt;				&lt; CollectionName & gt; ForeignKeys & lt;/ CollectionName & gt;				&lt; RestrictionName & gt; Table & lt;/ RestrictionName & gt;				&lt; RestrictionNumber & gt; 3 & lt;/ RestrictionNumber & gt;				&lt;/ Restrictions & gt;				&lt; Restrictions & gt;				&lt; CollectionName & gt; ForeignKeys & lt;/ CollectionName & gt;				&lt; RestrictionName & gt; Name & lt;/ RestrictionName & gt;				&lt; RestrictionNumber & gt; 4 & lt;/ RestrictionNumber & gt;				&lt;/ Restrictions & gt;				&lt; Restrictions & gt;				&lt; CollectionName & gt; ForeignKeyColumns & lt;/ CollectionName & gt;				&lt; RestrictionName & gt; Table & lt;/ RestrictionName & gt;				&lt; RestrictionNumber & gt; 3 & lt;/ RestrictionNumber & gt;				&lt;/ Restrictions & gt;				&lt; Restrictions & gt;				&lt; CollectionName & gt; ForeignKeyColumns & lt;/ CollectionName & gt;				&lt; RestrictionName & gt; Name & lt;/ RestrictionName & gt;				&lt; RestrictionNumber & gt; 4 & lt;/ RestrictionNumber & gt;				&lt;/ Restrictions & gt;				&lt; Restrictions & gt;				&lt; CollectionName & gt; ForeignKeyColumns & lt;/ CollectionName & gt;				&lt; RestrictionName & gt; Column & lt;/ RestrictionName & gt;				&lt; RestrictionNumber & gt; 5 & lt;/ RestrictionNumber & gt;				&lt;/ Restrictions & gt;				&lt; Restrictions & gt;				&lt; CollectionName & gt; Views & lt;/ CollectionName & gt;				&lt; RestrictionName & gt; Table & lt;/ RestrictionName & gt;				&lt; RestrictionNumber & gt; 3 & lt;/ RestrictionNumber & gt;				&lt;/ Restrictions & gt;				&lt; Restrictions & gt;				&lt; CollectionName & gt; ViewColumns & lt;/ CollectionName & gt;				&lt; RestrictionName & gt; Table & lt;/ RestrictionName & gt;				&lt; RestrictionNumber & gt; 3 & lt;/ RestrictionNumber & gt;				&lt;/ Restrictions & gt;				&lt; Restrictions & gt;				&lt; CollectionName & gt; ViewColumns & lt;/ CollectionName & gt;				&lt; RestrictionName & gt; Column & lt;/ RestrictionName & gt;				&lt; RestrictionNumber & gt; 4 & lt;/ RestrictionNumber & gt;				&lt;/ Restrictions & gt;				&lt;/ DocumentElement & gt;";
		//return SQLResource.ResourceManager.GetString(nameof (Restrictions), SQLResource.resourceCulture);
      }
    }

    internal static string StopWords_EN
    {
      get
      {
		return @"able
about
above
according
accordingly
across
actually
after
afterwards
again
against
ain't
all
allow
allows
almost
alone
along
already
also
although
always
am
among
amongst
an
and
another
any
anybody
anyhow
anyone
anything
anyway
anyways
anywhere
apart
appear
appreciate
appropriate
are
aren't
around
as
aside
ask
asking
associated
at
available
away
awfully
be
became
because
become
becomes
becoming
been
before
beforehand
behind
being
believe
below
beside
besides
best
better
between
beyond
both
brief
but
by
c'mon
c's
came
can
can't
cannot
cant
cause
causes
certain
certainly
changes
clearly
co
com
come
comes
concerning
consequently
consider
considering
contain
containing
contains
corresponding
could
couldn't
course
currently
definitely
described
despite
did
didn't
different
do
					does
					doesn't
doing
don't
done
down
downwards
during
each
edu
eg
eight
either
else
elsewhere
enough
entirely
especially
et
etc
even
ever
every
everybody
everyone
everything
everywhere
ex
exactly
example
except
far
few
fifth
first
five
followed
following
follows
for
former
formerly
forth
four
from
further
furthermore
get
gets
getting
given
gives
go
goes
going
gone
got
gotten
greetings
had
hadn't
happens
hardly
has
hasn't
have
haven't
having
he
he's
hello
help
hence
her
here
here's
hereafter
hereby
herein
hereupon
hers
herself
hi
him
himself
his
hither
hopefully
how
howbeit
however
i'd
i'll
i'm
i've
ie
if
ignored
immediate
in
inasmuch
inc
indeed
indicate
indicated
indicates
inner
insofar
instead
into
inward
is
isn't
it
it'd
it'll
it's
its
itself
just
keep
keeps
kept
know
knows
known
last
lately
later
latter
latterly
least
less
lest
let
let's
like
liked
likely
little
look
looking
looks
ltd
mainly
many
may
maybe
me
mean
meanwhile
merely
might
more
moreover
most
mostly
much
must
my
myself
name
namely
nd
near
nearly
necessary
need
needs
neither
never
nevertheless
new
next
nine
no
nobody
non
none
noone
nor
normally
not
nothing
novel
now
nowhere
obviously
of
off
often
oh
ok
okay
old
on
once
one
ones
only
onto
or
other
others
otherwise
ought
our
ours
ourselves
out
outside
over
overall
own
particular
particularly
per
perhaps
placed
please
plus
possible
presumably
probably
provides
que
quite
qv
rather
rd
re
really
reasonably
regarding
regardless
regards
relatively
respectively
right
said
same
saw
say
saying
says
second
secondly
see
seeing
seem
seemed
seeming
seems
seen
self
selves
sensible
sent
serious
seriously
seven
several
shall
she
should
shouldn't
since
six
so
some
somebody
somehow
someone
something
sometime
sometimes
somewhat
somewhere
soon
sorry
specified
specify
specifying
still
sub
such
sup
sure
t's
take
taken
tell
tends
th
than
thank
thanks
thanx
that
that's
thats
the
their
theirs
them
themselves
then
thence
there
there's
thereafter
thereby
therefore
therein
theres
thereupon
these
they
they'd
they'll
they're
they've
think
third
this
thorough
thoroughly
those
though
three
through
throughout
thru
thus
to
together
too
took
toward
towards
tried
tries
truly
try
trying
twice
two
un
under
unfortunately
unless
unlikely
until
unto
up
upon
us
use
used
useful
uses
using
usually
value
various
very
via
viz
vs
want
wants
was
wasn't
way
we
we'd
we'll
we're
we've
welcome
well
went
were
weren't
what
what's
whatever
when
whence
whenever
where
where's
whereafter
whereas
whereby
wherein
whereupon
wherever
whether
which
while
whither
who
who's
whoever
whole
whom
whose
why
will
willing
wish
with
within
without
won't
wonder
would
wouldn't
yes
yet
you
you'd
you'll
you're
you've
your
yours
yourself
yourselves
zero";
        //return SQLResource.ResourceManager.GetString(nameof (StopWords_EN), SQLResource.resourceCulture);
      }
    }
  }
}
